# Generated by Django 5.2.5 on 2025-09-28 15:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_producto_moneda_precio_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número único del pedido', max_length=20, unique=True)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del pedido', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('verificando', 'Verificando Pago'), ('pagado', 'Pagado'), ('rechazado', 'Pago Rechazado')], default='pendiente', help_text='Estado del pago', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('pago_movil', 'Pago Móvil'), ('zelle', 'Zelle'), ('paypal', 'PayPal'), ('binance', 'Binance Pay'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='efectivo', help_text='Método de pago seleccionado', max_length=20)),
                ('comprobante_pago', models.ImageField(blank=True, help_text='Comprobante de transferencia/pago móvil', null=True, upload_to='comprobantes/')),
                ('notas_pago', models.TextField(blank=True, help_text='Notas del usuario sobre el pago')),
                ('notas_administrador', models.TextField(blank=True, help_text='Notas del administrador sobre el pago')),
                ('fecha_pago', models.DateTimeField(blank=True, help_text='Fecha en que se verificó el pago', null=True)),
                ('direccion_entrega', models.TextField(help_text='Dirección de entrega')),
                ('telefono_contacto', models.CharField(help_text='Teléfono de contacto para la entrega', max_length=16)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del pedido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, help_text='Fecha programada de entrega', null=True)),
                ('administrador_pago', models.ForeignKey(blank=True, help_text='Administrador que verificó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento del pedido', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal de este item (cantidad × precio)', max_digits=10)),
                ('producto', models.ForeignKey(help_text='Producto del pedido', on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('pedido', models.ForeignKey(help_text='Pedido al que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(help_text='Producto en el carrito', on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('usuario', models.ForeignKey(help_text='Usuario propietario del carrito', on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'created_at'], name='pedidos_car_usuario_97e266_idx')],
                'unique_together': {('usuario', 'producto')},
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'estado'], name='pedidos_ped_usuario_cd8414_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pago', 'fecha_creacion'], name='pedidos_ped_estado__d9c9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='pedidos_ped_estado_fedc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='pedidos_ped_numero__426e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'producto'], name='pedidos_ite_pedido__2a9e41_idx'),
        ),
    ]
