# Generated by Django 5.2.5 on 2025-09-28 15:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_principal', models.CharField(choices=[('USD', 'Dólar Americano (USD)'), ('VES', 'Bolívar Venezolano (VES)'), ('COP', 'Peso Colombiano (COP)')], default='USD', help_text='Moneda principal del sistema', max_length=3)),
                ('mostrar_multiple_monedas', models.BooleanField(default=True, help_text='Mostrar precios en múltiples monedas')),
                ('monedas_mostrar', models.JSONField(default=list, help_text="Lista de monedas a mostrar (ej: ['USD', 'VES', 'COP'])")),
                ('decimales_precision', models.PositiveIntegerField(default=2, help_text='Número de decimales para mostrar precios')),
                ('simbolos_monedas', models.JSONField(default=dict, help_text="Símbolos de monedas (ej: {'USD': '$', 'VES': 'Bs', 'COP': '$'})")),
            ],
            options={
                'verbose_name': 'Configuración de Moneda',
                'verbose_name_plural': 'Configuraciones de Moneda',
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(choices=[('USD', 'Dólar Americano (USD)'), ('VES', 'Bolívar Venezolano (VES)'), ('COP', 'Peso Colombiano (COP)')], help_text='Moneda de origen', max_length=3)),
                ('moneda_destino', models.CharField(choices=[('USD', 'Dólar Americano (USD)'), ('VES', 'Bolívar Venezolano (VES)'), ('COP', 'Peso Colombiano (COP)')], help_text='Moneda de destino', max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, help_text='Tasa de cambio (1 unidad de origen = X unidades de destino)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta tasa está activa')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas sobre la tasa de cambio')),
                ('actualizada_por', models.ForeignKey(blank=True, help_text='Usuario que actualizó la tasa', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['moneda_origen', 'moneda_destino'],
                'unique_together': {('moneda_origen', 'moneda_destino')},
            },
        ),
    ]
