# Generated by assistant: add default EUR rate
from django.db import migrations
from decimal import Decimal


def create_eur_rate(apps, schema_editor):
    TasaCambio = apps.get_model('core', 'TasaCambio')
    # crear tasa USD -> EUR si no existe
    usd_eur, created = TasaCambio.objects.get_or_create(
        moneda_origen='USD',
        moneda_destino='EUR',
        defaults={
            'tasa': Decimal('0.85'),
            'activa': True,
        }
    )
    # crear inversa EUR -> USD
    try:
        if usd_eur.tasa and usd_eur.tasa != 0:
            inv = Decimal('1') / usd_eur.tasa
            TasaCambio.objects.get_or_create(
                moneda_origen='EUR',
                moneda_destino='USD',
                defaults={
                    'tasa': inv,
                    'activa': True,
                }
            )
    except Exception:
        pass


def remove_eur_rate(apps, schema_editor):
    TasaCambio = apps.get_model('core', 'TasaCambio')
    TasaCambio.objects.filter(moneda_origen='USD', moneda_destino='EUR').delete()
    TasaCambio.objects.filter(moneda_origen='EUR', moneda_destino='USD').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionmoneda_tasacambio'),
    ]

    operations = [
        migrations.RunPython(create_eur_rate, remove_eur_rate),
    ]
