# Generated by Django 5.2.5 on 2025-09-21 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (mínimo 2 caracteres)', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está disponible')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activa', 'orden'], name='catalogo_ca_activa_90d7a5_idx'), models.Index(fields=['slug'], name='catalogo_ca_slug_84a82a_idx')],
            },
        ),
    ]
