# Generated by Django 5.2.5 on 2025-09-22 00:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto (mínimo 3 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto (mínimo $0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Stock mínimo antes de alertar')),
                ('imagen', models.ImageField(help_text='Imagen principal del producto', upload_to='productos/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está disponible para venta')),
                ('destacado', models.BooleanField(default=False, help_text='Producto destacado en la página principal')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-destacado', '-created_at'],
                'indexes': [models.Index(fields=['activo', 'destacado'], name='catalogo_pr_activo_c84eea_idx'), models.Index(fields=['categoria', 'activo'], name='catalogo_pr_categor_cdb42d_idx'), models.Index(fields=['precio'], name='catalogo_pr_precio_de346d_idx'), models.Index(fields=['slug'], name='catalogo_pr_slug_17e2cc_idx')],
            },
        ),
    ]
