# Generated by Django 5.2.5 on 2025-09-28 15:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda_precio',
            field=models.CharField(choices=[('USD', 'Dólar Americano (USD)'), ('VES', 'Bolívar Venezolano (VES)'), ('COP', 'Peso Colombiano (COP)')], default='USD', help_text='Moneda del precio base', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto en la moneda base', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
